name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '--conventional-commits'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 12
          scope: '@optipack'
          always-auth: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: |
          git config --global user.name "SnO2WMaN"
          git config --global user.email "SnO2WMaN@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn install --frozen-lockfile
      - run: yarn lerna version ${{ github.event.inputs.version }} --yes --no-commit-hooks --create-release github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
